### ISSUE TITLE
[bug] timestamp formatting ignored now for output?

### ISSUE THREAD

**Issue by Gorrrg** [PetterKraabol/Twitch-Chat-Downloader#33]
It looks as if the date/time formatting is broken. This here...

`            "output": {
                "format": "{channel[name]} - {created_at} - {_id} - {title}.txt",
                "timestamp": {
                    "absolute": "%Y%m%d"
                }
            }`
produces a `OSError: [Errno 22] Invalid argument:` error because the string looks like `2017-12-27T13:30:00Z` despite the formatting.

**Comment by PetterKraabol** [comment]
Hi, use [custom variables](https://github.com/PetterKraabol/Twitch-Chat-Downloader/wiki/Custom-formats#custom-variables) for timestamps, rather than `{created_at}`. In this case it would be `{timestamp[absolute]}`.

It doesn't make much sense to specify it to be absolute, but it makes timestamp formatting consistent for output and comments.

**Comment by Gorrrg** [comment]
Ok I used that and added the timestamp absolute formatting. But it seems to be failing for SRT.
